### ISSUE TITLE
Executable `circleci-config-validate.sh` not found

### ISSUE THREAD

**Issue by ellisvalentiner** [syntaqx/git-hooks#1]
Running `pre-commit` fails because the shell script isn't found:

```bash
$ pre-commit run --all-files                      
black....................................................................Passed
Flake8...................................................................Passed
bandit...................................................................Passed
safety...................................................................Passed
CircleCI config validation...............................................Failed
hookid: circleci-config-validate

Executable `/Users/<redacted>/.cache/pre-commit/repo5_0lcvu4/hooks/circleci-config-validate.sh` not found
```

**Comment by syntaqx** [comment]
Hey there. Been sick, but I'll check this out in a couple days once I'm back on my feet!

**Comment by syntaqx** [comment]
@ellisvalentiner Which version of this project are you using? I just created a new repository, added a `.circleci/config.yml`, and the following `.pre-commit-config.yaml`:

```
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.6
  hooks:
    - id: circleci-config-validate
```

And:

```
$ pre-commit run --all-files
CircleCI config validation...............................................Passed
```

Could you give me more exact steps to reproduce? Perhaps ensuring you're also using the latest version of pre-commit, etc?

**Comment by ellisvalentiner** [comment]
Thanks for the response.

Here is my `.pre-commit-config.yaml`:

```yaml
repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
-   repo: https://github.com/PyCQA/bandit
    rev: 2a1dbab
    hooks:
    - id: bandit
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
    - id: python-safety-dependencies-check
-   repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.6
    hooks:
    - id: circleci-config-validate
```

I've ran `pre-commit autoupdate` as well.
